### ISSUE TITLE
I have discovered an error. : "TypeError: set_envparams() takes 2 positional arguments but 3 were given"

### ISSUE THREAD

**Issue by itsnils** [DFRobot/DFRobot_SGP40#1]
Hello Thanks for the Python library.
I have discovered an error. 

Error:
`    sgp40.set_envparams(50,-2)
TypeError: set_envparams() takes 2 positional arguments but 3 were given
`

Solution:
the self in this line is missing
https://github.com/DFRobot/DFRobot_SGP40/blob/9c2f48fe858f5195fa29bc581073206e539d0fbd/Python/raspberrypi/DFRobot_SGP40.py#L58

**Comment by fary99** [comment]
> 您好 感谢您提供 Python 库。
> 我发现了一个错误。
> 
> 错误：
> ` sgp40.set_envparams(50,-2) TypeError: set_envparams() takes 2 positional arguments but 3 were given`
> 
> 解决方法：
> 缺少这一行的self
> https://github.com/DFRobot/DFRobot_SGP40/blob/9c2f48fe858f5195fa29bc581073206e539d0fbd/Python/raspberrypi/DFRobot_SGP40.py#L58

Thanks for the feedback, it has been modified

**Comment by fary99** [comment]
> Hello Thanks for the Python library.
> I have discovered an error.
> 
> Error:
> ` sgp40.set_envparams(50,-2) TypeError: set_envparams() takes 2 positional arguments but 3 were given`
> 
> Solution:
> the self in this line is missing
> https://github.com/DFRobot/DFRobot_SGP40/blob/9c2f48fe858f5195fa29bc581073206e539d0fbd/Python/raspberrypi/DFRobot_SGP40.py#L58

Thanks for the feedback, it has been modified
